FROM ubuntu:20.04

# build
# docker build -t grew:latest .

# run
# docker run --rm -p 8001:8000 -p 8899:8899 --hostname localhost --name grewtest -it grew 

LABEL maintainer="Johannes Heinecke <johannes.heinecke@orange.com>"
LABEL org.label-schema.name="Grew Match server"
LABEL org.label-schema.version="2.0"
LABEL org.label-schema.schema_version="RC1"

ENV TZ="Europe/Paris"
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone    

RUN apt-get update \
	&& apt-get install -y git \
	&& apt-get install -y opam \
	&& apt-get install -y make wget m4 unzip librsvg2-bin curl bubblewrap \
	&& apt-get install -y pkg-config openssl libssl-dev \
	&& apt-get install -y libpcre3-dev sqlite3 zlib1g-dev \
	&& apt-get install -y libgmp3-dev libsqlite3-dev \
	&& apt-get install -y libcairo-dev

RUN opam init --disable-sandboxing
RUN opam switch create 4.14.0 4.14.0
RUN eval $(opam env)
ENV PATH=${PATH}:/root/.opam/4.14.0/bin

RUN opam remote add grew "http://opam.grew.fr"

RUN opam install --yes libcaml-dep2pict grew
RUN opam install --yes fileutils ocsipersist-sqlite eliom

WORKDIR /opt

RUN git clone https://gitlab.inria.fr/grew/grew_match.git
RUN git clone https://gitlab.inria.fr/grew/grew_match_back.git

RUN sed -i 's/PERSISTENT_DATA_BACKEND = dbm/PERSISTENT_DATA_BACKEND = sqlite/' /opt/grew_match_back/Makefile.options

RUN cat /opt/grew_match_back/gmb.conf.in__TEMPLATE \
	| sed 's:<log>__TODO__:<log>/opt/grew_match_back/log:' \
	| sed 's:<extern>__TODO__:<extern>/opt/grew_match_back/static:' \
	| sed 's:<corpora>__TODO__:<corpora>/opt/grew_match_back/corpora:' \
	| sed 's:<config>__TODO__:<config>/opt/grew_match/corpora/config.json:' \
	> /opt/grew_match_back/gmb.conf.in

COPY config.json /opt/grew_match/corpora/config.json
COPY welsh.json /opt/grew_match_back/corpora/welsh.json

RUN git clone https://github.com/UniversalDependencies/UD_Welsh-CCG.git

RUN grew compile -grew_match_server /opt/grew_match/meta -i /opt/grew_match_back/corpora/welsh.json

RUN mkdir /opt/grew_match_back/log

# # # todo: use /log and /corpora
# # # VOLUME [ "/opt/grew_match_back/log", "/opt/grew_match_back/corpora" ]

EXPOSE 8000

COPY startscript.sh .
RUN chmod +x startscript.sh

CMD ["/opt/startscript.sh"]
